# Generated by Django 2.1.5 on 2019-02-16 20:49

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=datetime.datetime.now)),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Professional', 'Professional'), ('Important', 'Important'), ('Sport', 'Sport'), ('Study', 'Study'), ('Other', 'Other')], default='', max_length=30)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10)),
            ],
        ),
    ]
